// main.cpp - DllMain, the main loop, hotkeys, arming, and the stage-3 invite-gate patch.
//
// Split out of the original single-file tw3k_coop.cpp. Behaviour is unchanged: this was pure
// code motion. ../tw3k_coop.ASBUILT.cpp remains the known-good single-file snapshot.

#include "tw3k.h"

// Which SOURCE this DLL was built from — see the SOURCE: line in the banner and the note beside it.
// `build_info.h` is generated by build.bat on every build and is not tracked, so the include is
// conditional: a fresh clone that has never run build.bat still compiles, and says "unknown", which
// is the truth in that case rather than a guess.
#if defined(__has_include)
#  if __has_include("build_info.h")
#    include "build_info.h"
#  endif
#endif
#ifndef TW3K_GIT
#  define TW3K_GIT "unknown - built without build.bat"
#endif
#define TW3K_GIT_STAMP TW3K_GIT

static const uint8_t EXPECTED_CMP[] = { 0x83, 0xBB, 0xCC, 0x00, 0x00, 0x00, 0x01 };
static constexpr size_t IMM_INDEX  = 6; // the "01" — max players minus one

HMODULE   g_selfModule  = nullptr; // OUR resident DLL
uintptr_t g_base        = 0;        // the GAME's image base (for RVA math)
bool      g_patched     = false;
uint8_t   g_originalImm = 0x01;

// Integrity watchdog: after we write the immediate, remember what it SHOULD be
// so the main loop can detect anti-tamper silently restoring it.
volatile bool    g_watch       = false;
volatile uint8_t g_expectedImm = 0x01;

// ★ Set by the pipe thread (`panic --yes` / `detach --yes`), DRAINED by the probe loop — which is
// the thread F1 and F12 ran on, so the work happens exactly where it always did. See the drain
// site for why this is a real requirement and not ceremony.
volatile long g_panicRequest  = 0;
volatile long g_detachRequest = 0;
// ⚠ Kept so the VEH can be REMOVED. See the install site and the detach tail — discarding it is how
// `detach` came to leave a live handler pointing into an unmapped module (#62).
PVOID g_crashWitnessHandle = nullptr;
// ⚠⚠ `crash test <kind> --yes`. Kills the game ON PURPOSE — see performCrashTest in crashdump.cpp.
volatile long g_crashTestRequest = 0;

// ------------------------------------------- ★★★ ARM WHEN READY, NOT WHEN INJECTED (session 6t)
//
// Until now the rule was "reach the main menu, THEN inject", and it existed because the checks above
// run once: inject too early, every signature fails, all nine hooks refuse to install, and the
// machine then spends the whole session looking healthy while doing nothing. That is the same
// silent-failure shape that has already cost this project several runs — it just arrives by a
// different route, and it is the single thing that made the injector hard to automate.
//
// So instead of getting the timing right from outside, remove the requirement: wait for our own
// preconditions. Denuvo decrypts lazily, so the honest statement is "the bytes are not there yet",
// and the honest response is to look again rather than to arm nothing.
//
// This also happens to run the experiment AUTOINJECT.md asks for. If injection at process-start is
// in fact fine, the log says "matched, first try". If it is not, the log says exactly how many
// seconds the wait was. Either way the answer arrives as a by-product of the first automated run
// instead of costing a dedicated test.
//
// Second-order wins: injecting mid-session now works, and so does re-injecting after F12.
static const int kArmPollMs     = 1000;
static const int kArmTimeoutSec = 600;   // generous: a cold Steam start under Denuvo is slow

static bool armWhenReady()
{
    diagLogf("---- verifying signatures ----");

    int unread = 0, bad = 0;
    if (verifyAllSignatures(true, &unread, &bad)) {
        logf("ALL SIGNATURES MATCHED — this machine's game build is the one we analysed.");
        return true;
    }

    logf("SIGNATURES NOT READY: %d unreadable, %d mismatched. EXPECTED if the game has not reached "
         "the main menu yet — waiting up to %d s, re-checking every %d ms. Hooks are installed below, "
         "once the bytes are actually there, so injecting early no longer means running un-hooked.",
         unread, bad, kArmTimeoutSec, kArmPollMs);

    const DWORD started = GetTickCount();
    int lastBucket = -1;

    for (;;) {
        Sleep(kArmPollMs);
        const int elapsed = (int)((GetTickCount() - started) / 1000);

        if (verifyAllSignatures(false, &unread, &bad)) {
            diagLogf("---- signatures came good after %d s; re-checking verbosely ----", elapsed);
            verifyAllSignatures(true);
            // Keep this string byte-identical to the first-try case: tools/TwMachines.ps1 greps for
            // it to decide whether a run is worth reading.
            logf("ALL SIGNATURES MATCHED — this machine's game build is the one we analysed. "
                 "(ready after %d s of waiting — injection timing did not matter)", elapsed);
            return true;
        }

        if (elapsed >= kArmTimeoutSec) break;

        // One progress line per 15 s bucket. Not change-triggered — a fixed heartbeat is what tells
        // you the wait is still alive, and it keeps a 10-minute wait to ~40 lines instead of 600.
        const int bucket = elapsed / 15;
        if (bucket != lastBucket) {
            lastBucket = bucket;
            diagLogf("   still waiting (%3d s): %d unreadable, %d mismatched", elapsed, unread, bad);
        }
    }

    logf("!! GAVE UP WAITING after %d s. Final state of every site:", kArmTimeoutSec);
    verifyAllSignatures(true, &unread, &bad);
    if (bad > 0 && unread == 0)
        logf("!! SIGNATURE MISMATCH — this machine's build DIFFERS. Send me the log; do not test here.");
    else
        logf("!! SIGNATURES NEVER APPEARED (%d unreadable, %d mismatched) — either the game never "
             "reached the main menu, or this build decrypts these sites differently. Send me the "
             "log; do not trust this machine's results.", unread, bad);
    return false;
}

// ------------------------------------------- ★★★ IS THIS THE BUILD THE RVAs CAME FROM? (2026-09-18)
//
// Every address this DLL uses is an RVA typed into offsets.h and added to `g_base`. Nothing is
// looked up by symbol, nothing is scanned for at runtime, and nothing is relocated: an RVA that was
// correct against one build is just a NUMBER against any other, and it lands wherever that number
// happens to land in that binary.
//
// On 2026-09-17 the game went 1.7.1 -> 1.7.2 (Denuvo removed, crossplay added) and all ~100 RVAs in
// offsets.h were re-derived against 1.7.2. A handful of sites verify their own bytes before writing
// and refuse individually — the invite gate below, every detourInstall/thunkRedirect, #75's three
// call spans, #69's seventeen. Those are safe on any build, because there a mismatch IS a refusal.
//
// MOST OF THE RVAs HAVE NOTHING OF THE KIND. The lobby singleton, the battle root, the event-cursor
// globals and every struct offset hung off them are dereferenced on the strength of the number
// alone. Attach to a 1.7.1 install and they read — and in several places WRITE — whatever happens
// to live at those addresses in that build, silently. The log would still say STAGE 1 OK, still
// print the same banner, and the first sign of trouble would be a corrupted save or a desync.
//
// ⇒ So ask the one question that separates the two builds, once, before anything is hooked or
// patched, and ask it of the PE headers of the image we are actually running inside. That is the
// only description of the running build that cannot be stale, cannot describe a different install
// than the one that launched, and cannot be wrong about itself.
//
// The wrong install is not hypothetical: a rollback, an older depot, or the machine on the rig that
// has not taken the update yet. That last one is this project's most repeated failure shape — the
// BUILD: line further down exists because two machines once silently ran an older DLL, and this is
// the same mistake with the roles reversed.
//
//   1.7.2   SizeOfImage 0x04836000 (75,718,656 bytes)   TimeDateStamp 0x69CE4C84  <-- what we target
//   1.7.1   SizeOfImage 0x0FD9B000 (265,920,512 bytes)  TimeDateStamp 0x68F237CC
//
// The 190,214,144-byte difference between them is the Denuvo `.xcode` section that 1.7.2 removed,
// which is why SizeOfImage alone separates the two so cleanly. TimeDateStamp is what makes the
// match build-EXACT rather than "something of about the right size", and it is what will catch
// 1.7.3 as well — a future build has no obligation to change size, but it always changes stamp.
//
// ⚠ Both pairs were read out of the two binaries' PE headers directly. If the game updates again
// they get re-read, not guessed, and they are updated in the SAME commit as the rebased RVAs: a
// fingerprint that trails the offsets it guards would wave through the exact case it exists for.
static constexpr uint32_t BUILD_172_SIZEOFIMAGE   = 0x04836000; // the build these RVAs were derived from
static constexpr uint32_t BUILD_172_TIMEDATESTAMP = 0x69CE4C84;
static constexpr uint32_t BUILD_171_SIZEOFIMAGE   = 0x0FD9B000; // the pre-update build, named on sight
static constexpr uint32_t BUILD_171_TIMEDATESTAMP = 0x68F237CC;

static bool verifyGameBuild()
{
    // Walked field by field with safeRead rather than by casting g_base to an IMAGE_DOS_HEADER*,
    // and the reason is the one the check itself rests on: this is the FIRST thing that touches the
    // image, it runs before a single site has been verified, and the whole premise is that we do not
    // yet know what this binary is. So every read is guarded, and an unreadable header FAILS CLOSED
    // — "I could not tell" is a refusal here, never a pass.
    uint32_t e_lfanew = 0;
    if (!safeRead((void*)(g_base + 0x3C), &e_lfanew, sizeof(e_lfanew))) {
        logf("!! BUILD CHECK: e_lfanew at %016llX is UNREADABLE — the running image's PE headers "
             "cannot be read, so which build this is cannot be established. Refusing to hook "
             "anything: an unverifiable build is treated exactly like a wrong one.",
             (unsigned long long)(g_base + 0x3C));
        return false;
    }
    // A sane e_lfanew is a small offset inside the first page. Anything else means this is not a PE
    // image at all, and every read below would be pointing at nothing in particular.
    if (e_lfanew < 0x40 || e_lfanew > 0x400) {
        logf("!! BUILD CHECK: e_lfanew reads %08X, which is not a plausible PE header offset. The "
             "image at %016llX is not shaped like the game. Refusing to hook anything.",
             e_lfanew, (unsigned long long)g_base);
        return false;
    }

    const uintptr_t pe = g_base + e_lfanew;

    uint32_t sig = 0;
    if (!safeRead((void*)pe, &sig, sizeof(sig))) {
        logf("!! BUILD CHECK: PE signature at %016llX is UNREADABLE. Refusing to hook anything.",
             (unsigned long long)pe);
        return false;
    }
    if (sig != 0x00004550) {   // "PE\0\0"
        logf("!! BUILD CHECK: %016llX holds %08X, not a PE signature (want 00004550). Whatever this "
             "process's main module is, it is not the binary these RVAs describe. Refusing to hook "
             "anything.", (unsigned long long)pe, sig);
        return false;
    }

    uint32_t stamp = 0;
    if (!safeRead((void*)(pe + 8), &stamp, sizeof(stamp))) {
        logf("!! BUILD CHECK: TimeDateStamp at %016llX is UNREADABLE. Refusing to hook anything.",
             (unsigned long long)(pe + 8));
        return false;
    }

    // The optional header follows the 4-byte signature and the 20-byte file header. Its magic is
    // checked rather than assumed, because SizeOfImage sits at a DIFFERENT offset in a PE32 optional
    // header — reading the right field out of the wrong header shape is precisely the class of
    // mistake this guard exists to stop, and it would be a poor place to make it.
    const uintptr_t opt = pe + 0x18;

    uint16_t magic = 0;
    if (!safeRead((void*)opt, &magic, sizeof(magic))) {
        logf("!! BUILD CHECK: optional header magic at %016llX is UNREADABLE. Refusing to hook "
             "anything.", (unsigned long long)opt);
        return false;
    }
    if (magic != 0x020B) {
        logf("!! BUILD CHECK: optional header magic is %04X, not 020B (PE32+). This is not the "
             "64-bit game image, and SizeOfImage would not even be where we are about to look. "
             "Refusing to hook anything.", (unsigned)magic);
        return false;
    }

    uint32_t sizeOfImage = 0;
    if (!safeRead((void*)(opt + 0x38), &sizeOfImage, sizeof(sizeOfImage))) {
        logf("!! BUILD CHECK: SizeOfImage at %016llX is UNREADABLE. Refusing to hook anything.",
             (unsigned long long)(opt + 0x38));
        return false;
    }

    // ---- the match. Both fields or nothing: SizeOfImage is what separates 1.7.2 from 1.7.1, and
    // TimeDateStamp is what stops "the right size" being mistaken for "the right build".
    if (sizeOfImage == BUILD_172_SIZEOFIMAGE && stamp == BUILD_172_TIMEDATESTAMP) {
        // Logged on the GOOD path too, deliberately: this is the line that proves the guard ran and
        // says what it saw, so a log from a healthy machine and a log from a refusing one can be
        // compared field by field without attaching a debugger to either.
        logf("BUILD FINGERPRINT OK: SizeOfImage %08X (%u bytes), TimeDateStamp %08X — this is 1.7.2, "
             "the build every RVA in offsets.h was derived from. The addresses below are being "
             "applied to the binary they were read out of.",
             sizeOfImage, (unsigned)sizeOfImage, stamp);
        return true;
    }

    // ---- the refusal. Observed values FIRST and unconditionally, so a mismatch nobody predicted is
    // still diagnosable from the log alone: the next unknown build gets identified by someone
    // reading these two numbers, not by reproducing it.
    logf("################ WRONG GAME BUILD — REFUSING TO HOOK ANYTHING ################");
    logf("!! OBSERVED: SizeOfImage %08X (%u bytes)   TimeDateStamp %08X   image base %016llX",
         sizeOfImage, (unsigned)sizeOfImage, stamp, (unsigned long long)g_base);
    logf("!! EXPECTED: SizeOfImage %08X (%u bytes)   TimeDateStamp %08X   = 1.7.2",
         BUILD_172_SIZEOFIMAGE, (unsigned)BUILD_172_SIZEOFIMAGE, BUILD_172_TIMEDATESTAMP);

    if (sizeOfImage == BUILD_171_SIZEOFIMAGE && stamp == BUILD_171_TIMEDATESTAMP) {
        logf("!! THIS IS 1.7.1 — the PRE-UPDATE build, matched exactly on both fields. This DLL's "
             "addresses were rebased to 1.7.2 on 2026-09-17, so on this binary every one of them "
             "points at something else. UPDATE THIS MACHINE TO 1.7.2; do not force the DLL onto "
             "1.7.1. (The usual causes: a rollback, an older Steam depot, or the one PC on the rig "
             "that has not taken the update yet — check the others before blaming the mod.)");
        logf("!! If 1.7.1 genuinely has to be played, check out the DLL from BEFORE the rebase "
             "rather than running this one. The RVAs are the difference, not the build date.");
    }
    else if (sizeOfImage == BUILD_171_SIZEOFIMAGE || stamp == BUILD_171_TIMEDATESTAMP) {
        logf("!! ONE FIELD MATCHES 1.7.1 (SizeOfImage %08X / TimeDateStamp %08X) and the other does "
             "not — 1.7.1-shaped, but not the 1.7.1 these numbers were read from. A hotfix, or a "
             "depot in between. Treat it as UNRECOGNISED: the RVAs have to be re-derived against "
             "THIS binary rather than forced onto it.",
             BUILD_171_SIZEOFIMAGE, BUILD_171_TIMEDATESTAMP);
    }
    else if (sizeOfImage == BUILD_172_SIZEOFIMAGE) {
        logf("!! SAME SIZE AS 1.7.2 BUT A DIFFERENT TimeDateStamp — a rebuild or hotfix PAST the "
             "build these RVAs were derived from. The same size is not the same code: re-derive the "
             "offsets against this binary and update this fingerprint with them. Do NOT widen the "
             "check to SizeOfImage alone to make this pass.");
    }
    else {
        logf("!! UNRECOGNISED BUILD — neither 1.7.2 nor 1.7.1 (1.7.1 is SizeOfImage %08X, "
             "TimeDateStamp %08X). RE-DERIVE the RVAs against this binary rather than forcing this "
             "DLL onto it: most of them have no signature behind them, so on the wrong build they "
             "read — and in places write — whatever happens to live at those addresses. Re-run the "
             "Ghidra rebase, then record the new fingerprint beside the new offsets.",
             BUILD_171_SIZEOFIMAGE, BUILD_171_TIMEDATESTAMP);
    }

    logf("!! Nothing has been hooked and no game byte has been written. Compare the BUILD: and "
         "SOURCE: lines above across all machines, then send me this log.");
    logf("##############################################################################");
    return false;
}

// ------------------------------------------- "am I armed?", answerable without parsing the log
//
// One named mutex per game process, held for as long as this DLL is loaded. Two jobs:
//
//   * a watcher can ask "is this PID already injected?" and get an answer in microseconds — no log
//     to parse, and no module enumeration against a Denuvo-protected process;
//   * a second injection into the same process is refused instead of running the probe thread twice.
//
// Named with the PID rather than a fixed string, because the question is always about one specific
// game process, and a per-PID name cannot outlive its process and make the next launch look armed.
//
// Global\ first, so a watcher running elevated (which it must be, to OpenProcess the game) sees it
// across integrity levels; Local\ as fallback, because creating a Global\ object needs
// SeCreateGlobalPrivilege and the game's own token may not have it. Failing both is not fatal — it
// only costs the watcher its fast path, and the log still says everything.
static HANDLE g_armedMutex = nullptr;
static char   g_armedMutexName[64] = "";

static bool claimArmedMutex()
{
    const DWORD pid = GetCurrentProcessId();
    static const char* const kPrefixes[] = { "Global\\", "Local\\" };

    for (const char* prefix : kPrefixes) {
        char name[64];
        _snprintf_s(name, sizeof(name), _TRUNCATE, "%stw3k_coop_armed_%lu", prefix, pid);

        SetLastError(0);
        HANDLE h = CreateMutexA(nullptr, FALSE, name);
        const DWORD err = GetLastError();

        if (h && err == ERROR_ALREADY_EXISTS) { CloseHandle(h); return false; }
        if (h) {
            g_armedMutex = h;
            strcpy_s(g_armedMutexName, sizeof(g_armedMutexName), name);
            return true;
        }
    }
    return true;
}

static void releaseArmedMutex()
{
    if (g_armedMutex) { CloseHandle(g_armedMutex); g_armedMutex = nullptr; }
}

static void removeShareHook() { detourRemove(g_shareDetour, "share hook"); }

// ---------------------------------------------------------------- stage 3

// Verify the whole instruction before touching anything.
#ifndef TW3K_RELEASE
static bool verifyInviteSite()
{
    const uintptr_t site = g_base + RVA_INVITE_CMP;
    uint8_t found[sizeof(EXPECTED_CMP)] = { 0 };

    if (!safeRead((void*)site, found, sizeof(found))) {
        logf("invite gate: UNREADABLE at %016llX", (unsigned long long)site);
        return false;
    }

    char hex[64] = { 0 };
    for (size_t i = 0; i < sizeof(found); ++i)
        _snprintf_s(hex + i * 3, 4, _TRUNCATE, "%02X ", found[i]);
    logf("invite gate @ %016llX bytes: %s", (unsigned long long)site, hex);

    for (size_t i = 0; i < sizeof(EXPECTED_CMP); ++i) {
        if (found[i] != EXPECTED_CMP[i]) {
            logf("invite gate: SIGNATURE MISMATCH at byte %zu (want %02X got %02X) "
                 "— refusing to patch", i, EXPECTED_CMP[i], found[i]);
            return false;
        }
    }
    logf("invite gate: signature OK (max players currently %u)",
         (unsigned)EXPECTED_CMP[IMM_INDEX] + 1);
    return true;
}
#endif

// Write the immediate. maxPlayers=4 writes 0x03 ("disable when count > 3").
#ifndef TW3K_RELEASE
static bool setInviteMax(uint8_t maxPlayers)
{
    if (maxPlayers < 2) return false;
    const uintptr_t imm = g_base + RVA_INVITE_CMP + IMM_INDEX;
    const uint8_t   val = (uint8_t)(maxPlayers - 1);

    DWORD oldProtect = 0;
    if (!VirtualProtect((void*)imm, 1, PAGE_EXECUTE_READWRITE, &oldProtect)) {
        logf("patch: VirtualProtect failed, err=%lu", GetLastError());
        return false;
    }

    uint8_t before = *(volatile uint8_t*)imm;
    *(volatile uint8_t*)imm = val;
    FlushInstructionCache(GetCurrentProcess(), (void*)imm, 1);
    uint8_t after = *(volatile uint8_t*)imm;

    DWORD tmp = 0;
    VirtualProtect((void*)imm, 1, oldProtect, &tmp);

    if (after != val) {
        // Write silently reverted => something is protecting/restoring the page.
        logf("patch: WRITE DID NOT STICK (wrote %02X, reads back %02X) — "
             "memory is protected or being restored", val, after);
        return false;
    }

    logf("patch: %02X -> %02X OK (invite now allowed while players < %u)",
         before, after, (unsigned)maxPlayers);
    g_patched     = (val != g_originalImm);
    g_expectedImm = val;
    g_watch       = true;   // arm the integrity watchdog
    return true;
}
#endif


// Re-read the immediate; if it no longer matches what we wrote, anti-tamper
// restored it. This is the decisive test for whether code patching is viable.
#ifndef TW3K_RELEASE
static void integrityCheck()
{
    if (!g_watch) return;
    const uintptr_t imm = g_base + RVA_INVITE_CMP + IMM_INDEX;
    uint8_t cur = 0;
    if (!safeRead((void*)imm, &cur, 1)) {
        logf("WATCHDOG: invite byte became UNREADABLE (page changed under us)");
        g_watch = false;
        return;
    }
    if (cur != g_expectedImm) {
        logf("WATCHDOG: !! EXTERNAL REVERT !! wrote %02X, now reads %02X "
             "-> anti-tamper is restoring code. Code patching is NOT viable.",
             g_expectedImm, cur);
        g_watch = false; // report once
    }
}
#endif


// ---------------------------------------------------------------- main loop

// ---------------------------------------------------------------- crash logger
//
// ★★★ WHY THIS EXISTS (2026-08-04). a client crashes to desktop joining a lobby, and it is
// reproducible on two machines. All the log gives us is where it STOPPED — which is not the same as
// what killed it, and the difference has already cost one wrong diagnosis: an out-of-bounds write
// this file's author introduced was a perfect fit for the timing and turned out not to be the cause.
//
// A vectored exception handler converts every future repro into an answer: the exception code, the
// faulting instruction, the address that was touched, whether it was a READ or a WRITE, and — the
// part that decides whose bug it is — **which module owns the faulting instruction**.
//
// ⚠ It does not change behaviour. It logs and returns EXCEPTION_CONTINUE_SEARCH, so the game still
// handles or dies exactly as it would have. This is a witness, not a handler.
//
// ⚠ Filtered hard on purpose. A game throws and catches first-chance exceptions constantly (C++ EH
// is 0xE06D7363, and it is normal traffic); logging those would bury the file and slow the process.
// Only the codes that actually kill a process get a line, and only the first few.
//
// ★★ THE BUDGET IS PER SIGNATURE, NOT PER FAULT (2026-08-16). It used to be `> 4` against a
// process-lifetime counter, which had a failure mode that was only a matter of time: the game
// throws fatal-CLASS exceptions it then handles — a guard-page read, a probe of an unmapped page —
// and four of those spend the entire budget. The CTD that arrives twenty minutes later then gets
// **no line at all**, leaving the witness silent in exactly the situation it exists for. That is
// the same shape as the `raises performed=0` trap in HANDOVER: a counter read long before the
// moment that mattered.
//
// So a fault that REPEATS is counted and stays quiet, and a fault that is NEW always gets its full
// block. Fixed table, no allocation, no lock — this runs inside an exception handler, where the
// heap may already be the thing that broke and where taking a lock the faulting thread might
// already hold would deadlock the crash report.
struct FaultSig { DWORD code; uintptr_t at; long count; };
#ifndef TW3K_RELEASE
static FaultSig      g_faults[32] = {};
static volatile long g_faultKinds = 0;
static volatile long g_faultTotal = 0;

// True when this exact (code, address) pair has already been reported, in which case it is only
// counted. A race here costs a duplicate line and nothing else, which is the right trade against
// locking inside a fault.
static bool faultSeenBefore(DWORD code, uintptr_t at)
{
    InterlockedIncrement(&g_faultTotal);

    const long cap = (long)(sizeof(g_faults) / sizeof(g_faults[0]));
    const long n   = g_faultKinds;
    for (long i = 0; i < n && i < cap; ++i)
        if (g_faults[i].code == code && g_faults[i].at == at) { ++g_faults[i].count; return true; }

    if (n >= cap) return true;                  // table full — count only, stop printing
    g_faults[n].code = code; g_faults[n].at = at; g_faults[n].count = 1;
    g_faultKinds = n + 1;
    return false;
}

long faultKindsSeen()  { return g_faultKinds; }
long faultsSeenTotal() { return g_faultTotal; }

static LONG CALLBACK crashWitness(EXCEPTION_POINTERS* ep)
{
    if (!ep || !ep->ExceptionRecord) return EXCEPTION_CONTINUE_SEARCH;

    const DWORD code = ep->ExceptionRecord->ExceptionCode;
    switch (code) {
        case EXCEPTION_ACCESS_VIOLATION:
        case EXCEPTION_IN_PAGE_ERROR:
        case EXCEPTION_ILLEGAL_INSTRUCTION:
        case EXCEPTION_PRIV_INSTRUCTION:
        case EXCEPTION_STACK_OVERFLOW:
        case EXCEPTION_INT_DIVIDE_BY_ZERO:
        case EXCEPTION_ARRAY_BOUNDS_EXCEEDED:
            break;
        default:
            return EXCEPTION_CONTINUE_SEARCH;    // first-chance C++ EH and friends — normal traffic
    }

    const uintptr_t at = (uintptr_t)ep->ExceptionRecord->ExceptionAddress;

    // Repeats are counted, not printed. `crash` reports both numbers, so a fault that fires ten
    // thousand times is still visible as ten thousand — it just does not write ten thousand lines.
    if (faultSeenBefore(code, at)) return EXCEPTION_CONTINUE_SEARCH;

    // ★★★ STACK OVERFLOW LEAVES WITHOUT WRITING A WORD (2026-08-17, measured live).
    //
    // Everything below this line — `owner[260]`, `path[260]`, and above all `logf`, which formats
    // into 2.2 KB of stack buffers BEFORE it writes a byte — is affordable on every fault except
    // this one. Windows dispatches EXCEPTION_STACK_OVERFLOW on the stack that just overflowed, with
    // roughly one page left, of which the CONTEXT record alone takes 1,232 bytes.
    //
    // ⚠ The first live overflow test spent that page HERE. The log ended at `Going down now.` with
    // no FAULT block, no FATAL block and no dump — not even a truncated line, because `logf` is
    // all-or-nothing: it formats first and writes once. A witness trying to describe the crash was
    // the reason nothing described the crash.
    //
    // ⇒ The signature is already counted above, so `crash` still reports it. The dumper thread —
    //   which has its own fresh stack — writes the banner, the faulting address AND the module
    //   attribution for this path. See crashdump.cpp's logFatalPreamble.
    //
    // ✗ Do NOT "improve" this by logging a short line here. There is no short `logf`: the 2.2 KB is
    //   in the buffers, not in the message.
    if (code == EXCEPTION_STACK_OVERFLOW) return EXCEPTION_CONTINUE_SEARCH;

    // ★ THE LINE THAT DECIDES WHOSE BUG IT IS. If the faulting instruction is inside our own DLL,
    // it is ours; if it is inside Three_Kingdoms.exe, it is the game's code — which may still be
    // running on state we corrupted, but it narrows the search enormously either way.
    char owner[MAX_PATH] = "(unknown module)";
    HMODULE mod = nullptr;
    if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                           GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                           (LPCSTR)at, &mod) && mod) {
        char path[MAX_PATH] = { 0 };
        if (GetModuleFileNameA(mod, path, MAX_PATH)) {
            const char* leaf = strrchr(path, '\\');
            _snprintf_s(owner, sizeof(owner), _TRUNCATE, "%s  (base %016llX, +0x%llX)",
                        leaf ? leaf + 1 : path, (unsigned long long)(uintptr_t)mod,
                        (unsigned long long)(at - (uintptr_t)mod));
        }
    }

    logf("################ FAULT ################");
    logf("  code=%08lX at %016llX", code, (unsigned long long)at);
    logf("  module: %s", owner);
    logf("  OURS=%s", (mod && mod == g_selfModule) ? "YES — the fault is in tw3k_coop.dll"
                                                   : "no — not our module");

    if (code == EXCEPTION_ACCESS_VIOLATION || code == EXCEPTION_IN_PAGE_ERROR) {
        const ULONG_PTR kind = ep->ExceptionRecord->ExceptionInformation[0];
        const ULONG_PTR addr = ep->ExceptionRecord->ExceptionInformation[1];
        logf("  %s %016llX",
             kind == 0 ? "READ from" : kind == 1 ? "WROTE to" : "DEP violation at",
             (unsigned long long)addr);
        // A tiny value is a null-pointer deref with an offset; a huge one is usually a bad index.
        if (addr < 0x10000)
            logf("     (that is a NULL pointer plus a small offset — a field read off a null object)");
        else if (addr > 0x00007FFFFFFFFFFFull)
            logf("     (non-canonical — a garbage pointer, not merely a freed one)");
    }

#ifdef _M_X64
    if (ep->ContextRecord) {
        const CONTEXT* c = ep->ContextRecord;
        logf("  RIP=%016llX RSP=%016llX RCX=%016llX RDX=%016llX",
             (unsigned long long)c->Rip, (unsigned long long)c->Rsp,
             (unsigned long long)c->Rcx, (unsigned long long)c->Rdx);
        logf("  R8 =%016llX R9 =%016llX RAX=%016llX RBX=%016llX",
             (unsigned long long)c->R8, (unsigned long long)c->R9,
             (unsigned long long)c->Rax, (unsigned long long)c->Rbx);
        // ★ RDI and RSI were missing from the first version and were the two that mattered: in
        // FUN_14057BEB0 — the duplicate-widget-name descendant walk — RDI is the NODE being walked
        // and RSI the candidate list. Without RDI the 2026-08-04 fault could say a children pointer
        // was garbage but not which object owned it.
        logf("  RDI=%016llX RSI=%016llX RBP=%016llX R10=%016llX",
             (unsigned long long)c->Rdi, (unsigned long long)c->Rsi,
             (unsigned long long)c->Rbp, (unsigned long long)c->R10);

        // For that fault specifically: dump the node RDI points at, so the next repro says what kind
        // of object the walk descended into. +0x124 is read as a child COUNT and +0x128 as the
        // children ARRAY, so those two fields are the whole question.
        if (c->Rdi > 0x10000 && c->Rdi < 0x00007FFFFFFFFFFFull) {
            uint32_t childCount = 0; uint64_t childArray = 0, vtable = 0;
            readAt((uintptr_t)c->Rdi, vtable);
            readAt((uintptr_t)c->Rdi + 0x124, childCount);
            readAt((uintptr_t)c->Rdi + 0x128, childArray);
            logf("  node at RDI: vtable=%016llX  childCount(+0x124)=%u  children(+0x128)=%016llX",
                 (unsigned long long)vtable, childCount, (unsigned long long)childArray);
        }
        // The game has no ASLR slide, so an image-relative address can be pasted straight into
        // Ghidra. Say it explicitly rather than leaving the arithmetic to whoever reads this.
        if (g_base && at > g_base && at < g_base + 0x20000000ull)
            logf("  ⇒ Ghidra address for the faulting instruction: %016llX",
                 (unsigned long long)at);
    }
#endif
    logf("################ END FAULT ################");
    return EXCEPTION_CONTINUE_SEARCH;            // let the game die exactly as it would have
}

#endif
static DWORD WINAPI probeThread(LPVOID)
{
    // Refuse to run twice in one process. Deliberately BEFORE resetLog(): a second injection must not
    // create a second timestamped log file, because two files from one run read exactly like two runs.
    if (!claimArmedMutex()) {
        OutputDebugStringA("tw3k_coop: this process is already injected — second copy doing nothing\r\n");
        return 0;
    }

    resetLog();

#ifndef TW3K_RELEASE
    // First, before any hook exists: a crash during attach should still be witnessed.
    //
    // ⚠⚠ THE HANDLE IS KEPT, AND THAT IS LOAD-BEARING (2026-08-17, #62). It used to be discarded,
    // which made the VEH impossible to remove — and a VEH is called on EVERY first-chance exception
    // in the process, including the constant C++ EH traffic this game generates (0xE06D7363, see the
    // filter at the top of crashWitness). So after `detach` unmapped this DLL, the process's own
    // handler chain still held a pointer to `crashWitness` in freed memory, and the very next throw
    // jumped into an unmapped page. ⇒ That is why detach kills the game AFTER it reports success,
    // rather than at the moment of detaching. See the detach tail below.
    g_crashWitnessHandle = AddVectoredExceptionHandler(1, &crashWitness);
    if (g_crashWitnessHandle)
        logf("crash witness: installed. A fatal exception will print FAULT with the faulting "
             "instruction, the address touched, and WHICH MODULE owns the code — read-only, and the "
             "game still dies exactly as it would have.");

    // ★ The other half of the witness: a MINIDUMP, taken from inside the dying process. The witness
    // prints what somebody thought to print; the dump answers the questions nobody thought of, which
    // is the rule Capture-TwDump.ps1 exists to serve — and that script cannot serve it for a crash,
    // because procdump attaches to a process that is still running. Every CTD this project has had
    // was reconstructed from a log line for exactly that reason.
    //
    // ⚠ It hangs off SetUnhandledExceptionFilter, NOT the witness's VEH, so nothing is written for a
    // first-chance fault the game was about to handle. That is what makes it safe to leave on in a
    // lockstep session: no stall, no desync, and by the time it does write, the peer has lost this
    // client anyway. See crashdump.cpp for the re-arm, which is not optional.
    if (installCrashDumper())
        logf("crash dumper: installed — a crash now leaves tw3k_crash_%s_<stamp>.dmp beside the log. "
             "Compact by default (a few MB, sub-second); `crash heap on` swaps in the full ~8.6 GB "
             "dump for a session. Changes no execution.", g_hostName);

#endif
    // Identify the machine INSIDE the file as well as in its name — a copied or renamed log should
    // still be attributable to a specific PC without guesswork.
    {
        // Hostname only — GetUserNameA would drag in advapi32 for no diagnostic value.
        SYSTEMTIME st{};
        GetLocalTime(&st);
        logf("==== tw3k_coop attached ====");
        // Compile-time stamp. Counting hooks in the banner was an unreliable way to spot a stale
        // DLL: in run 5 two machines silently ran an older build. A loaded DLL is memory-mapped and
        // therefore LOCKED, so if the game is still running from a previous attempt, robocopy cannot
        // replace the file and leaves the old one in place. This line makes that unambiguous —
        // compare it across the three logs before trusting a run.
        logf("BUILD MODE: %s", TW3K_BUILD_MODE);
        logf("BUILD: %s %s   <-- must MATCH on all machines; if not, that PC ran a stale DLL",
             __DATE__, __TIME__);

        // ★★ AND WHICH SOURCE IT CAME FROM (2026-08-05).
        //
        // tester, after a session ran while this repo was being moved between ten feature branches:
        // *"i'm not sure if working on all these branches is such a good idea on the same machine."*
        // He is right, and the hazard is sharper than it sounds: `runtime/tw3k_coop.dll` is TRACKED, so
        // `git checkout <branch>` silently rewrites the very file `Deploy-TwMod.ps1` pushes to every
        // machine. A deploy taken mid-session would have shipped whatever branch happened to be out,
        // and the timestamp below would have looked perfectly normal.
        //
        // ⇒ The timestamp cannot answer "which code is this?" — only "when was it compiled". This
        // line can. `build.bat` passes the branch and short commit in, plus `+dirty` when the tree
        // has uncommitted changes, so **every log says exactly which source built the DLL that
        // wrote it** and a stale or wrong-branch build stops depending on anyone remembering.
        //
        // Unknown rather than absent when git is unavailable: a helper unzipping a release has no
        // repo, and "unknown" is the truth there.
        logf("SOURCE: %s   <-- the branch and commit this DLL was built from", TW3K_GIT_STAMP);

        // ★★ HOW THIS DLL GOT INTO THE PROCESS (2026-08-05).
        //
        // The delivery route is being swapped — injector.exe is what antivirus and an ISP are
        // flagging, and `amd_ags_x64.dll` (the forwarder the game loads itself) is what replaces it.
        // Until now a log could not tell the two apart, which is precisely the distinction that
        // decides whether a test of the new route proved anything at all.
        //
        // The proxy sets TW3K_LOADED_BY before it calls LoadLibrary. Anything else — injector.exe,
        // a manual LoadLibrary, the watcher — leaves it unset, and "unset" is reported as what it
        // is rather than assumed to be injection.
        {
            char how[64] = { 0 };
            const DWORD n = GetEnvironmentVariableA("TW3K_LOADED_BY", how, sizeof(how));
            if (n > 0 && n < sizeof(how) && _stricmp(how, "proxy") == 0)
                diagLogf("LOADED BY: the amd_ags_x64.dll PROXY — the game loaded this itself. "
                     "Nothing injected, no remote thread, no watcher.");
            else
                diagLogf("LOADED BY: injection or an unknown route (TW3K_LOADED_BY is not set). "
                     "That is the old path — see runtime/proxy/README.md.");
        }
        logf("MACHINE: %s", g_hostName);
        diagLogf("LOCAL TIME AT ATTACH: %04u-%02u-%02u %02u:%02u:%02u",
             st.wYear, st.wMonth, st.wDay, st.wHour, st.wMinute, st.wSecond);
        logf("LOG FILE: %s   (unique per machine+run — just copy it, no renaming needed)", g_logPath);
        diagLogf("ARMED MUTEX: %s   (a watcher tests this instead of parsing this file)",
             g_armedMutexName[0] ? g_armedMutexName : "(none — could not create one)");
    }

    g_base = (uintptr_t)GetModuleHandleA(nullptr); // game's base for RVA math
    diagLogf("STAGE 1 OK: DLL is running inside the game. image base = %016llX%s",
         (unsigned long long)g_base,
         g_base == 0x140000000 ? " (preferred, no ASLR slide)" : " (ASLR slide applied)");

    // ★★★ THE BUILD GATE, and it is FIRST on purpose: g_base is now known, and nothing has yet been
    // hooked, patched, armed or even read through an RVA. If this is not the binary the RVAs were
    // derived from, the correct amount of work to do is none — see verifyGameBuild above for why
    // most of those RVAs cannot notice on their own.
    //
    // It refuses by ending the probe thread here. That is the whole mechanism, and it is the same
    // one the second-injection check at the top of this function uses: no hook is installed because
    // every install call is below this line, and none of them is reached. No detour, no code write,
    // no control pipe, no probe loop. The DLL stays resident and completely inert, and the game runs
    // exactly as it would have without it.
    //
    // ⚠ The armed mutex is deliberately NOT released. It means "this process already has the DLL in
    // it", which remains true — dropping it would invite Watch-TwInject.ps1 to inject again, and
    // again, into the same wrong-build process, each attempt writing another timestamped log that
    // reads like another run. Teardown keeps it for the same reason; see the tail of this function.
    if (!verifyGameBuild()) {
        diagLogf("==== tw3k_coop is INERT on this machine: no hooks, no patches, no control pipe. "
             TW3K_MODE_TEXT("`ping` will not answer here — that silence is the symptom, and this log is the ", "the mod will remain inert here — that silence is the symptom, and this log is the ")
             "reason. Fix the build, then relaunch the game. ====");
        return 0;
    }

    // Wait for the game to decrypt the sites we hook, rather than requiring the human to inject at
    // the right moment. Returns false only after the timeout, and even then we still attempt the
    // installs below: each detour re-verifies its own bytes and refuses individually, so the log
    // ends on the familiar "NOT ALL HOOKS INSTALLED" line rather than on silence.
    armWhenReady();

    // Deliberately AFTER arming. This reads a code byte too, so running it first on an early
    // injection only produced a scary UNREADABLE line about a gate the join hook superseded anyway.
    TW3K_DIAGNOSTIC(verifyInviteSite());

    // The slot fix is now AUTO-INSTALLED. Manual staging existed so that a crash could be blamed on
    // a specific hook, and it did its job — but that risk is now retired (signatures are verified
    // before every write, Denuvo endurance passed, and two 3-machine runs installed these cleanly).
    //
    // Meanwhile the opposite risk kept biting: in the run of 2026-07-29 player 3 pressed F4 but not
    // F5, so that machine ran without the seat hook, seated everyone with the stock last-match rule,
    // and ended up with a different local slot layout than the other two — which is why it never
    // registered in the lobby. That is the third session in a row lost to a keypress. A hook every
    // machine needs is a hook nobody should have to remember.
    diagLogf("---- auto-installing the slot fix + probes (every machine needs all of these) ----");
    const bool okGuard = installLobbyGuard();
    const bool okSaveLobby = installSaveLobbyHook();
    installFreshFactionHook();
    logf("B4 save-lobby: hook=%s armed=%s", okSaveLobby ? "active" : "FAILED",
         saveLobbyFixArmed() ? "yes" : "no");
    const bool okMp    = installMpHook();
    const bool okJoin  = installJoinHook();
    const bool okSeat  = installSeatHook();
    const bool okPanel = installPanelHook();
    const bool okSlotCh = installSlotChangedHook();
    const bool okTick   = installTickHook();
    const bool okReset  = installPanelResetHook();
    const bool okLeaveCache = installLeaveCacheGuard();
    logf("B4 leave-cache: hook=%s fix=%s", okLeaveCache ? "active" : "FAILED",
         leaveCacheFixArmed() ? "ARMED" : "off");
    // ★ B9 (#12): auto-installed, because it is a crash FIX and the crash it prevents happens while
    // the fourth player is being SEATED — long before anyone could reach for a command. `treewalk
    // off` disarms it if it ever needs to be A/B'd against vanilla.
    const bool okTree   = installTreeWalkGuard();
    // ★ RUN 7: the share hook was F6-gated ("only if you reach a battle") and so was never installed
    // — every capture that run read `share=off`. A battle WAS fought and produced no share data at
    // all, which is the one thing still needed to finish unit gifting. It is read-only (it logs, then
    // calls the original) and it mirrors the original's own null/empty-selection precondition before
    // touching anything, so there is no reason to make anyone remember it.
    const bool okShare  = installShareHook();
    // ★ The HUD constructor hook is installed SEPARATELY and is deliberately not part of the
    // nine-hook health check, nor of verifyAllSignatures. It is experimental, it only does anything
    // once F9 arms it, and a machine must not be reported as un-armed — or blocked from arming at
    // all — because an experiment's signature did not match. detourInstall verifies its own bytes
    // and refuses on its own, which is the check that actually matters here.
    if (installHudCtorHook())
        logf(TW3K_MODE_TEXT("HUD ctor hook: installed (inert until F9 arms it; see run 21/22 in NETCODE_NOTES.md)", "HUD ctor hook: installed (automatic spectator lending)"));
    else
        logf("HUD ctor hook: NOT installed — the participant-HUD experiment is unavailable, but "
             "everything else on this machine is unaffected.");

    // Read-only, and outside the health check for the same reason as the HUD ctor hook: a machine
    // must not read as un-armed because an experiment's signature did not match. It logs the
    // pending-battle participant list every time anyone picks a pre-battle option — which a SINGLE
    // PLAYER campaign is enough to exercise, so the offsets can be proved without a rig (§6hhh).
#ifndef TW3K_RELEASE
    if (installBattleRoleHook())
        logf("Pre-battle role hook: installed (read-only). Attack something and choose fight or "
             "auto-resolve; watch for 'PENDING-BATTLE PARTICIPANTS'.");
    else
        logf("Pre-battle role hook: NOT installed — the participant-list probe is unavailable, and "
             "nothing else on this machine is affected.");

#endif
    // B1: the campaign command executor. Also read-only and also outside the health check. It only
    // COUNTS — the counts print on F3 — because it runs from the campaign tick and logging each
    // command as it executed would bury a campaign, which is the failure NETCODE_NOTES warned about.
    // #63: cursor storage for the 3rd and 4th human. Outside the health check for the same reason
    // as the probes above — but note the asymmetry: a machine WITHOUT this must not run a 3-player
    // campaign at all, because the corruption it prevents is the engine's own write. The report in
    // `capture` says so in as many words.
    // #47/#50: the telestration participant map. READ-ONLY — it calls the original constructor and
    // then walks the map it built, so an un-armed and an armed client differ only in what they LOG.
    // It is installed unconditionally for the same reason `capture` is: the state it reads exists
    // only during a battle, and asking for it afterwards is asking for a session that already ended.
    if (installTelestrationHook()) {
        diagLogf("Telestration probe: installed (#47/#50). Silent until a battle builds the manager; "
             TW3K_MODE_TEXT("then every `capture` says which ping/arrow slots this client holds.", "then the local log records which ping/arrow slots this client holds."));

        // ★★★ ARMED AT ATTACH since 2026-08-18, and it is the same argument as `sidegate`: the
        // constructor leaves a player out of the participant map, and a client that has not applied
        // the fix is the broken one. ✅ PROVEN IN GAME the same night — the shut-out player's entry
        // was inserted (`entries inserted=1`) and their own `mgr+0x78` wiring repaired
        // (`own entry repaired=1`), and DRAWING came back for them.
        //
        // ⚠ It cannot desync: the telestration map is a UI object fed by chat, not lockstep state.
        // But arm it EVERYWHERE regardless — a machine without it still cannot see the strokes of
        // whoever it left out of its own map.
        //
        // ✗ It does NOT fix PINGS. Those are a different message (`chat_ping_msg` vs
        // `chat_telestration_msg`) with their own gate, and #47/#50 are therefore TWO bugs, not one
        // — see the telestration block in NETCODE_NOTES.md.
        const char* why = nullptr;
        if (setTelestrationFix(true, &why))
            logf("   >>> and ARMED automatically. Nothing to type; it applies from the next battle.");
        else
            logf("   ⚠ could NOT be armed automatically: %s", why ? why : "(no reason given)");
    }
    else
        logf("⚠ Telestration probe: NOT installed — #47/#50 cannot be measured on this client.");

    // ★★ #69 — the IconPath crash, armed here rather than by command, and the argument is that it is
    // provably BEHAVIOUR-PRESERVING rather than that it is useful.
    //
    // It reorders 17 bytes so `FUN_142F5EBA0` null-checks its source item before dereferencing the
    // property bag. On the non-null path every instruction still runs, in the same order relative to
    // anything that reads it. On the null path it skips a load whose result that path never uses —
    // read out of the function twice over: the spill at `+0x30` is read only inside the non-null
    // branch, and RBX is rewritten before the null path touches it.
    //
    // ⇒ The only behaviour that changes is the one where the game currently dies. And the patch
    // verifies all 17 bytes AND that its branch target still begins with `MOV RAX,[R12]` before it
    // writes anything, so a game update moves it out of the way rather than into something else.
    //
    // ⚠ It is applied HERE, at attach, on purpose: a 17-byte code write wants no thread executing
    // inside those bytes, and at attach no campaign UI exists to be inside them.
    if (!patchFeedIconGuard())
        logf("⚠ #69 feed icon guard: NOT applied — this client keeps the vanilla crash. Harmless "
             "unless an event-feed entry is presented with an empty feed, which is exactly the "
             "2026-08-14 signature.");

    // ★★★ #13/B10 — the same treatment, and for the same reason: it is a correctness fix, not an
    // experiment. Above two humans the engine hands a player with no army in the battle `armies[0]`,
    // which is the ATTACKER, and builds them as it. One byte widens the descriptor builder's
    // `humans == 2` to `humans >= 2`; at exactly two humans nothing changes at all.
    //
    // ⚠ Applied at attach for the same reason as #69: a code write wants no thread inside those
    // bytes, and at attach no battle exists to be in them.
    if (!patchBystanderSideGate())
        logf("⚠⚠ #13 side gate: NOT applied — above two humans this client will put its spectators "
             "on the ATTACKER's side, and it now DISAGREES with any client that did apply it. Do "
             TW3K_MODE_TEXT("not play a 3+ player session on this build until `ping` shows the patch everywhere.", "not play a 3+ player session on this build until every local log shows the patch applied."));

    // Production #56 containment belongs outside release-excluded diagnostic blocks.
    if (!installEventReadHook())
        logf("Event read containment NOT installed; native reopening behavior retained");

    // Install maintenance before arming any feature that depends on the campaign tick.
    if (installCampaignTickHook())
        logf(TW3K_MODE_TEXT("Campaign tick hook: installed — drains `answer` and maintains the human-faction ", "Campaign tick hook: installed — maintains the human-faction ")
             TW3K_MODE_TEXT("count hold and optional registry repair.", "count hold."));
    else
        logf(TW3K_MODE_TEXT("Campaign tick hook: NOT installed — `answer`, count hold and registry repair ", "Campaign tick hook: NOT installed — count hold ")
             "cannot run. Do not use this client for a 3+ human campaign.");

    if (installEventCursorHooks()) {
        logf("Event-cursor hooks: installed (write + read + gate byte). Inert until "
             TW3K_MODE_TEXT("humanFactionCount passes 2 — see the EVENT CURSORS block in F3.", "humanFactionCount passes 2 — cursor storage is maintained automatically."));

        // ★★★ #63's COUNT HOLD NOW ARMS ITSELF (2026-08-15), and the reasoning matters more than
        // the two lines of code.
        //
        // It shipped disarmed under the standing rule that an UNPROVEN writer defaults off, so an
        // un-armed client is byte-for-byte vanilla. It is not unproven any more: three campaigns,
        // four players with every seat receiving events, and a reloaded save played through turn
        // cycles — firing `found 2 -> wrote N` exactly once each time and standing.
        //
        // ⇒ Arming here is SAFER than the command was, not riskier. The rule it has to satisfy is
        // EVERY MACHINE OR NONE, and every machine running this DLL now arms identically and derives
        // the same value from the same replicated registry — satisfied BY CONSTRUCTION, rather than
        // by three people typing a command in the right order before every start and every load.
        // That step was missed twice and cost a session each time.
        //
        // ⚠ THE FAILURE MODE THAT REMAINS is a machine whose mod did not load, or which runs a
        // different build: it keeps the clamped count while the others raise it, and a count
        // mismatch in replicated model state is a desync by construction. `ping` before a session is
        // what catches that — it answers out of the RUNNING process, which is the only check that
        // has ever caught this class.
        const char* why = nullptr;
        if (setHumanFactionCountHold(true, &why))
            logf(">>> #63 COUNT HOLD: ARMED AUTOMATICALLY. A 3rd/4th player's events are collected "
                 "with nobody arming anything. It raises humanFactionCount only to the number of "
                 "registered human factions, never beyond, never lowers it, and is a no-op below "
                 TW3K_MODE_TEXT("three humans. `hfcount off` stops future raises and leaves the present count in place ", "three humans. ")
                 "— every machine or none, exactly as before. <<<");
        else
            logf("!! #63 COUNT HOLD: could NOT auto-arm — %s. ⚠ A 3rd or 4th player on this machine "
                 "will lose every event, and this client's count will differ from the others'. Do "
                 "not run a 3-player campaign against this build; send me this log.",
                 why ? why : "preconditions not met");
    }
    else
        logf("Event-cursor hooks: NOT installed — ⚠ this machine must NOT take part in a 3-player "
             "campaign, since a 3rd human's end turn would write over the list size at +0x1F8.");

    // The HUMAN_FACTIONS resolver is installed with the cursor lifetime hooks above. It
    // still logs saved IDs, and now also invalidates unsaved side cursors on reload.

#ifndef TW3K_RELEASE
    if (installCommandExecHook())
        logf("Command executor hook: installed (read-only, counts only). F3 prints what the campaign "
             "has been told to do, and the change since the previous F3.");
    else
        logf("Command executor hook: NOT installed — the command-traffic probe is unavailable, and "
             "nothing else on this machine is affected.");

    // ★ The event-feed ticker. Read-only, outside the health check for the same reason as the other
    // probes. It REPLACES the sampler that used to poll +0x14C/+0x14D every 2 s and, to find the
    // object to poll, swept every committed private region — 11.8 GB on a live game, every 10 s,
    // silently. That sweep is the 2026-08-10 battle-load slowdown. The hook needs no search at all:
    // the engine hands it the object.
    if (installFeedTickHook())
        logf("Event feed ticker hook: installed (read-only). Every branch taken is now SEEN rather "
             "than sampled — `feed` reports the counts, `feed off` silences the per-transition lines.");
    else
        logf("Event feed ticker hook: NOT installed — the B1 feed evidence is unavailable on this "
             "machine, and nothing else is affected.");

    // ★ The listener the ticker's event actually reaches. §6uuu's turn-guard mechanism was refuted
    // on 2026-08-13 — the guard passed and no box appeared — so this reads the step AFTER it and
    // says which of three things happened. Read-only, outside the health check like the other probes.
    if (installNextAutoOpenHook())
        logf("Auto-open listener hook: installed (read-only). `NextAutoOpenEventContext` now reports "
             "whether it refused at the turn guard, walked and accepted nothing, or produced a "
             "context — which is the split B1 has never had.");
    else
        logf("Auto-open listener hook: NOT installed — B1's next step is unreadable on this machine, "
             "and nothing else is affected.");

    // ★★★ #60 — the NOTIFICATION moment, upstream of everything else here. The observer callback
    // `FUN_142FCC780` is gated on "is the CURRENT faction human"; if that refuses, the feed is never
    // told the event exists and nothing retries. In single player that gate is the same test as the
    // listener's own guard, and the two come apart only in coop — which makes it the first
    // coop-specific-by-construction candidate B1 has produced. Read-only, and it settles the
    // hypothesis either way. Filtered by return address, since the predicate is a shared leaf.
    if (installFeedGateHook())
        logf("Feed notify-gate hook: installed (read-only). `feed` now reports whether the event feed "
             "is even TOLD an event exists — the step upstream of every other probe here.");
    else
        logf("Feed notify-gate hook: NOT installed — the notification moment is unreadable on this "
             "machine, and nothing else is affected.");

    // ★ The clause inside the walk that takes the LOCAL faction, and therefore the only one that can
    // make an identically-replicated record behave differently per client. Filtered by return
    // address to the walk's own call site, so the other four callers stay silent.
    if (installFactionInListHook())
        logf("Auto-open exclusion hook: installed (read-only). `exclusion` reports whether this "
             "faction is on the record's list, and who else is on it.");
    else
        logf("Auto-open exclusion hook: NOT installed — the named-predicate half of B1 is unreadable "
             "here, and nothing else is affected.");

#endif
    // ★ PLAN E FIRST, and plan D only if it could not install.
    //
    // They do the same job by opposite means: E answers for names the engine's own scan misses,
    // D overwrites entries the engine already has. Running both would hide E behind D — the scan
    // would find the hijacked name and never miss, so the fallback would never be exercised and the
    // run would prove nothing. So it is one or the other, deliberately.
    //
    // The fallback is for a failure to INSTALL, which is loud and immediate. If E installs but the
    // UI never reaches it, that is the experiment's answer, and F6 still restores the proven
    // F10 + gift-icon path for the rest of the battle.
    if (!installCcoResolverHook()) {
        diagLogf("CCO: plan E did not install — falling back to plan D, which is proven. The gift UI "
             "will work; it just spends the two dev entries again.");
        installCcoHijack();
    }

    if (okGuard && okMp && okJoin && okSeat && okPanel && okSlotCh && okTick && okReset && okShare
        && okTree)
        logf(">>> All ten core lobby/gift hooks active. Campaign maintenance and blending report separately. <<<");
    else
        logf("!! NOT ALL HOOKS INSTALLED (guard=%d mp=%d join=%d seat=%d panel=%d slotch=%d tick=%d "
             "reset=%d share=%d tree=%d) — send me this log, do not rely on this machine's results",
             okGuard, okMp, okJoin, okSeat, okPanel, okSlotCh, okTick, okReset, okShare, okTree);

    // ✗ The block that stood here listed twelve keys, and it was the single most misleading thing
    // the DLL printed: grepping the logs for an action name returned one hit PER LOG - the banner,
    // never a press - which reads as heavy use and is none. It also said "FREE: F7 ... nothing reads
    // them" while F7 was B1's recovery key, and was read as authoritative during an F7 test on
    // 2026-08-05.
    //
    // ⇒ It now describes what EXISTS rather than what can be pressed, and there is nothing left for
    // a count to confuse: one key, and it says so.
#ifndef TW3K_RELEASE
    logf("CONTROL: over the pipe, not the keyboard. Every hook installs itself - nobody needs to");
    logf("   press or type anything to PLAY. These are diagnostics, experiments and recovery.");
    logf("     pwsh -File Invoke-TwControl.ps1 -Command help");
    logf("   That script ships in coop_mod_twtk.zip and works with no repo, no remoting and no");
    logf("   credentials - it talks to this process on this machine.");
    logf("   ★ Read-only unless the command says WRITES. `capture` is the one worth knowing.");
    logf("★★ 2026-08-11: THE FUNCTION KEYS ARE GONE - the ACTIONS ARE NOT. Each moved to the pipe:");
    logf("     F1 panic -> `panic --yes`      F7  unblock -> `unblock --yes`");
    logf("     F3 capture -> `capture`        F8  faction -> `faction next`");
    logf("     F5 session -> `session`        F10 gift    -> `gift <id>` | `gift off`");
    logf("     F6 gift panel -> `panel on|off`  F12 detach -> `detach --yes`");
    logf("   Measured first: across 72 logs the keys fired TWICE, and one was F1 pressed by");
    logf("   accident - which ruins a run and looks like the mod failing.");
    logf("   ⚠ The pipe is also SAFER for the two that write: it is addressed to one process, and");
    logf("   B1's 'every machine or none' rule lands in ms across three machines, not three seconds");
    logf("   across three keyboards.");
    logf("   Ctrl+F4 = arm REMATCH UNLOCK (an experiment; off by default) - THE ONLY KEY LEFT, and");
    logf("   it is modifier-gated so it cannot be hit in passing.");
#endif
    diagLogf("SLOT EXPANSION IS AUTOMATIC (target 4) - no keypress needed, watch for 'AUTO-EXPAND DONE'.");
    diagLogf("NOBODY NEEDS TO PRESS ANYTHING TO PLAY. Host the lobby and invite; the slot count, the "
         "seating and the joining players' factions are all handled automatically.");
    diagLogf("   ...and as of run 28 that now includes BATTLES: a spectator in a multiplayer battle is "
         "built able to receive and command lent units with no keypress. Watch for "
         "'AUTO LENDING SPECTATOR' when the battle loads.");
    diagLogf("Injection timing no longer matters either - the DLL waits for the game's code to be ready "
         "before it hooks anything (see 'verifying signatures' above).");

#ifdef TW3K_RELEASE
    for (uint32_t tick = 0;; ++tick) {
        tickTurnBlendAutoArm(tick);
        // ★ This watch captures lobby names used by the player panel repair (#11).
        if ((tick % 5) == 0) watchLobbyPlayers();
        Sleep(100);
    }
#else
    uint32_t lastCount = 0xFFFFFFFF;
    uintptr_t lastMp = 0;
    bool fRem = false;
    uint32_t tick = 0;

    for (;;) {
        // Turn blending arms itself as soon as its sites have decrypted. It is a feature, not an
        // experiment, and this project has lost three sessions to a hook that needed a keypress.
        tickTurnBlendAutoArm(tick);

        // Passive stage-2 signal: log whenever the live player count changes,
        // and AUTO-DUMP the first time it becomes non-zero so we never miss the
        // populated-lobby moment.
        uint32_t count = 0;
        if (readAt(g_base + RVA_LOBBY_SINGLETON + OFF_PLAYER_COUNT, count) &&
            count != lastCount && count <= 64) {
            logf("STAGE 2: player count changed %u -> %u", lastCount, count);
            uint32_t prev = lastCount;
            lastCount = count;
            if (count > 0 && (prev == 0xFFFFFFFF || prev == 0)) {
                logf("STAGE 2: count is now non-zero — auto-dumping lobby");
                dumpLobbyState();
            }
        }

        // Change detector: snapshot the lobby object ~2x/sec and log any byte
        // that moves. This is how we find the REAL player-count field when a
        // player joins, without trusting a single guessed offset.
        if ((tick % 5) == 0) detectChange(false);

        // Integrity watchdog: check the patched byte ~once/sec (loop = 100ms).
        if ((tick % 10) == 0) integrityCheck();

        // B1: sample the turn state twice a second and log only what CHANGES. The bug has twice
        // refused to appear on demand, so the capture must not depend on anyone pressing F3 at the
        // right moment. Read-only, and silent outside a campaign.
        if ((tick % 5) == 0) watchCampaignTurns();

        // B4: same reasoning, one layer up. The engine's refresh runs a handful of times per
        // session, so a watch hanging off it is blind for most of a lobby's life — which is how a
        // four-player lobby came and went with `count=2` as the last thing logged.
        if ((tick % 5) == 0) watchLobbyPlayers();


        // Auto-report the moment the MP session object is captured by the hook.
        if (g_mpDetour.active) {
            const uintptr_t mp = capturedMp();
            if (mp && mp != lastMp) {
                lastMp = mp;
                logf("MP hook: CAPTURED EMPIRE_MP = %016llX", (unsigned long long)mp);
                dumpMpSession();
            }
        }

        // ★ THE CONTROL CHANNEL — a command is a keypress without a keyboard. See control.cpp.
        //
        // Deliberately wired at ONE site, and this one: commands execute on THIS thread, at THIS
        // point in the loop, so anything reachable by a hotkey below is reachable by a command with
        // identical semantics and no new concurrency to reason about.
        //
        // Both calls are idempotent — startControlServer() returns immediately once its thread is
        // up, and the drain returns immediately when nothing is queued — which keeps the wiring to
        // one place rather than one call at attach and another here.
        startControlServer();
        drainControlCommand();

        // Only this machine's own game reacts — see gameHasFocus(). Without this, a keypress sent
        // over remote desktop fires on the local AND the remote game simultaneously.
        // ⇒ A pipe command needs no such gate: it is addressed to one process by construction.
        const bool focused = gameHasFocus();
        // The rematch experiment's key lives in REMATCH_KEY / REMATCH_NEEDS_CTRL, not here, so it can
        // be re-bound without touching this loop. While it shares a key with another action, holding
        // the modifier suppresses that action so one press never fires two things.
        const bool ctrlDown = focused && (GetAsyncKeyState(VK_CONTROL) & 0x8000) != 0;
        const bool kRem = focused && (GetAsyncKeyState(REMATCH_KEY) & 0x8000) != 0
                          && (!REMATCH_NEEDS_CTRL || ctrlDown);
        // ★★★★ 2026-08-11 — THE BARE FUNCTION KEYS ARE GONE. Every action moved to the pipe.
        //
        // ⚠⚠ READ THIS BEFORE RE-ADDING ONE. What was retired is the BINDING, never the capability:
        // each key's action is reachable over the named pipe, and `Invoke-TwControl.ps1` ships inside
        // `coop_mod_twtk.zip` with a STANDALONE mode, so an off-LAN helper with no repo still has
        // every one of them. That distinction is the whole argument — `lobby.cpp` records a previous
        // pass that declared F8 retired, was WRONG, and was caught by the user, because that one
        // removed the capability itself.
        //
        // Measured across the 72 logs in tklogs/ before doing this — counting the ACTION line, not
        // the help banner, which is what made a first count read 72/72/73:
        //
        //     F6, F7, F10 .... 0 presses      F1 ............. 1 press
        //     F8 ............. 0 (auto-faction did the job 16 times, 16 successes)
        //
        // ⇒ The keys fired twice in 72 logs and one of the two was PANIC, pressed by accident.
        //   F7 in particular has never been pressed, while `answer` over the pipe recovered B1
        //   three times — the pipe had already won before this change ratified it.
        //
        //   F1  panic          -> `panic --yes`        F7  unblock  -> `unblock --yes`
        //   F3  full capture   -> `capture`            F8  faction  -> `faction next`
        //   F5  session dump   -> `session`            F10 gift     -> `gift <id>` / `gift off`
        //   F6  gift panel     -> `panel on|off`       F12 detach   -> `detach --yes`
        //
        // ★ Why the pipe is not merely equal but BETTER for the two that write: it is addressed to
        // one process by construction, so `gameHasFocus()` — which exists only because a keypress
        // over remote desktop fired on two machines at once — stops being load-bearing; and B1's
        // "every machine or none" rule lands in milliseconds across three machines instead of three
        // seconds across three keyboards.
        //
        // ✗ The comment that stood here claimed "FREE KEYS: F6, F7. Nothing reads them" while both
        // were read and dispatched twelve lines below it. That is the species of defect that made a
        // banner authoritative during an F7 test on 2026-08-05. Kept as a warning, not as history.
        //
        // ONE key remains, and deliberately: Ctrl+F4, the rematch experiment. It is modifier-gated
        // (so it cannot be hit in passing), off by default, and short-lived.
        // ★ PANIC, over the pipe now. `panic --yes` sets the request; it is DRAINED HERE, on the
        // same thread that used to run it off F1, so the fourteen removals happen exactly where they
        // always did. The pipe thread only sets a long.
        //
        // ⚠ That is the point of the flag, and it is not ceremony: `removeXHook()` walks a detour's
        // bookkeeping, and doing fourteen of them from the pipe thread while this loop is mid-pass
        // would be a race the old code never had. Same discipline as `queueFactionRequest`, which
        // says so in `lobby.cpp` — set a value, let the owning thread apply it.
        if (InterlockedExchange(&g_panicRequest, 0) != 0) {
            logf("PANIC: removing all hooks");
            setSaveLobbyWatch(false);
            if (g_rematchUnlocked) setRematchUnlock(false);
            if (g_turnBlendOn)     setTurnBlend(false);
            if (g_refreshBlendOn)  setRefreshBlend(false);
            removeJoinHook(); removeSeatHook(); removePanelHook();
            removeSlotChangedHook(); removeShareHook(); removeHudCtorHook();
            removeBattleRoleHook(); removeCommandExecHook(); removeEventCursorHooks();
            removeTelestrationHook();   // #47/#50 — read-only, and see the note below on why that
                                        // is not a reason to leave it installed
            // ⚠ The two read-only B1 probes were MISSING from both this list and the detach one until
            // 2026-08-13. Read-only makes a hook safe to LEAVE RUNNING, not safe to leave INSTALLED:
            // Both paths now retain the DLL, but omitted removers still leave behavior patched.
            // Panic is listed too, so the two paths
            // cannot drift.
            removeHumanFactionLoadHook();
            removeEventReadHook();
            removeFeedTickHook(); removeNextAutoOpenHook(); removeFactionInListHook();
            removeFeedGateHook();       // ⚠ was called NOWHERE until 2026-08-17 — see the detach tail
            removeCampaignTickHook();
            removeCcoHijack(); removeCcoResolverHook();
            removeTickHook(); removeFreshFactionHook(); removeSaveLobbyHook(); removePanelResetHook(); removeLeaveCacheGuard();
            removeTreeWalkGuard();
            unpatchFeedIconGuard();     // #69 — code bytes, so it belongs with the hooks, not the
                                        // switches: leaving it after FreeLibrary would be fine, but
                                        // panic means "make this process vanilla again"
            unpatchBystanderSideGate(); // #13 — same reasoning. ⚠ It also makes this client
                                        // DISAGREE with the others about army ownership, so panic
                                        // mid-session is a 3+ player desync risk, not just a revert.
            unpatchUpdateNullGuard();   // #75 — same reasoning again. A no-op unless somebody
                                        // armed it; it ships disarmed.
            removeLobbyGuard(); removeMpHook();
        }
        // `detach --yes`. Breaking the loop is what runs the restore-everything tail below, so this
        // has to be drained here rather than acted on from the pipe thread.
        if (InterlockedExchange(&g_detachRequest, 0) != 0) { logf("detach requested"); break; }
        // ⚠⚠ `crash test <kind> --yes` — DRAINED HERE AND DOES NOT RETURN. Same discipline as the two
        // above, plus a reason of its own: a fault raised on the pipe thread would kill the process
        // with the reply half-written, so the one piece of evidence anybody was waiting for would be
        // the piece that never arrived. Exchanged to zero FIRST, so a resumed fault (which would be a
        // finding — see performCrashTest) cannot re-fire on the next pass.
        {
            const long ct = InterlockedExchange(&g_crashTestRequest, 0);
            if (ct != 0) performCrashTest(ct);
        }
        // Un-grey the post-battle Rematch button in a multiplayer battle. OFF BY DEFAULT: until
        // pressed, nothing is read, nothing is written, and the build is byte-for-byte the one that
        // already works. Unlike the participant-HUD experiment below, this one can be armed at any
        // time — the predicate is evaluated when the battle-results screen is built, so any moment
        // before the battle ends is soon enough.
        if (kRem && !fRem) {
            if (setRematchUnlock(!g_rematchUnlocked)) {
                if (g_rematchUnlocked)
                    logf(">>> REMATCH UNLOCK: ARMED. FUN_142EE6E30 now returns 1, so the Rematch "
                         "button will be clickable on the post-battle results screen even though "
                         "this is a multiplayer battle. Press the same key again to restore the "
                         "original bytes."
                         "\n    Nothing has happened yet — the test is what the CLICK does. Expect "
                         "one of: (a) both clients restart the battle, (b) nothing, (c) a desync or "
                         "crash. Report which, and whether every client behaved the same.");
                else
                    logf(">>> REMATCH UNLOCK: disarmed — original bytes restored, vanilla behaviour.");
            }
        }
        // ⚠ EVERY key with an `if (kN && !fN)` above MUST be latched here — this is not style.
        //
        // `f7` was once declared and tested and never assigned, so `!f7` was permanently true and F7
        // ran on EVERY pass of this loop while the key was held — ten times a second, not once per
        // press. For that key it mattered: `Ctrl+F7` deliberately bypassed the safety rule that
        // stops it cutting a live operation short, so holding it for one second bypassed that rule
        // ten times.
        //
        // ⇒ If a key is ever added above, add it here in the SAME edit. The bug is invisible in
        // review precisely because the declaration, the test and the latch are three screens apart.
        //
        // ★ One key is left, which is why this warning survives the retirement rather than going
        // with it. A pipe command cannot have this bug — it arrives once, by construction.
        fRem = kRem;
        ++tick;

        // ⚠ Every 2 s, re-take the last-chance filter. SetUnhandledExceptionFilter keeps exactly ONE
        // per process, the proxy runs our DllMain BEFORE the game's own startup, and the game
        // installs its filter afterwards — so installing once at attach means the dumper is silently
        // gone by the time the main menu appears. That is the stale-DLL failure in a new costume:
        // everything reads armed and nothing is. Each re-arm chains to whoever displaced us, so the
        // game's own handler still runs and still decides the outcome. `crash` reports the count.
        if ((tick % 20) == 0) rearmCrashDumper();

        Sleep(100);
    }

#endif // debug loop; shared teardown remains paired in both preprocessed modes

    // Leave no patched code behind: the game keeps running after F12, and a stray `MOV AL,1 / RET`
    // would silently outlive the DLL that explains it.
#ifndef TW3K_RELEASE
    if (g_rematchUnlocked) {
        logf("restoring the rematch predicate before detach");
        setRematchUnlock(false);
    }
#endif
    if (g_turnBlendOn) {
        diagLogf("restoring the turn gate before detach");
        setTurnBlend(false);
    }
    if (g_refreshBlendOn) {
        diagLogf("restoring the UI refresh emitters before detach");
        setRefreshBlend(false);
    }
#ifndef TW3K_RELEASE
    if (g_patched) {
        logf("restoring original byte before detach");
        g_watch = false;
        setInviteMax(2);
        g_watch = false;
    }
    if (g_lobbyDetour.active) reportLobbyGuard();
    setSaveLobbyWatch(false);
    if (g_seatDetour.active)  reportSeatHook();
#endif
    removeJoinHook();
    removeSeatHook();
    removePanelHook();
    removeSlotChangedHook();
    removeTickHook();
    removeSaveLobbyHook();
    removeFreshFactionHook();
    removePanelResetHook();
    removeLeaveCacheGuard();
    removeShareHook();
    removeHudCtorHook();
#ifndef TW3K_RELEASE
    removeBattleRoleHook();
#endif
#ifndef TW3K_RELEASE
    removeCommandExecHook();
#endif
    removeEventCursorHooks();
    removeTelestrationHook();   // #47/#50 — read-only, and therefore exactly the kind this list loses
    // ⚠ See the note in the panic path: these are read-only, which is why they were overlooked, and
    // it is exactly the wrong reason to skip them here — this function UNLOADS the DLL.
    removeHumanFactionLoadHook();
    // ★★★★ THE ONE THE panic-vs-detach DIFF COULD NOT SEE (2026-08-17). `removeFeedGateHook()` was
    // called in NEITHER list — it existed in probes.cpp and nothing referenced it — so comparing the
    // two lists against each other reported them as agreeing. They agreed on being wrong.
    //
    // `installFeedGateHook` detours the event-feed NOTIFY GATE, which fires on turn transitions. In
    // `panic` that omission is harmless: the module stays mapped, so the detour still lands on real
    // code. Under `detach` it is fatal on the next transition — which is exactly what was observed,
    // on the first press of END TURN after a detach that otherwise looked clean.
    //
    // ⇒ The bisect that settled the class: `panic --yes` on a live campaign does NOT crash, and
    //   `detach --yes` did in the historical unload path (now removed). So whatever
    //   survived had to be a code pointer, not a state change.
    //
    // ⇒ Test-TwTeardown.ps1 now audits INSTALLERS against removers as well as list-against-list,
    //   because the list-vs-list diff is structurally blind to anything absent from both. §6uuu.48.
#ifndef TW3K_RELEASE
    removeFeedGateHook();
#endif
#ifndef TW3K_RELEASE
    removeFeedTickHook();
#endif
    removeEventReadHook();
#ifndef TW3K_RELEASE
    removeNextAutoOpenHook();
#endif
#ifndef TW3K_RELEASE
    removeFactionInListHook();
#endif
    removeCampaignTickHook();
    removeCcoHijack();
    removeCcoResolverHook();
    unpatchFeedIconGuard();     // #69 — see the panic path
    unpatchBystanderSideGate(); // #13 — see the panic path
#ifndef TW3K_RELEASE
    unpatchUpdateNullGuard();   // #75 — see the panic path
#endif
    // ★★★★ #62's PRIME SUSPECT, AND IT WAS MISSING FROM THIS LIST ONLY (found 2026-08-17 by
    // mechanically diffing this list against panic's — one call differed, and this was it).
    //
    // `treewalk` is a DETOUR on the widget name lookup and it is ON BY DEFAULT (#12/B9: a corrupt
    // child list makes the lookup fail instead of crashing). Panic removed it; detach never did. So
    // after `FreeLibraryAndExitThread` the widget name lookup still jumped into our unmapped code —
    // and widget name lookups happen constantly in the UI, which is exactly the observed shape:
    // a clean detach, the game still running, and a crash a short while later.
    //
    // ⚠ The panic block twelve hundred lines up warns in as many words that these two lists must not
    // drift — "detour still pointing at our code jumps into unloaded memory" — and it had drifted
    // anyway. ⇒ The lists are now compared mechanically rather than by reading; see §6uuu.47.
    removeTreeWalkGuard();
    removeLobbyGuard();
    removeMpHook();
    // Byte restoration does not prove that callbacks/trampolines have finished. Keep this
    // module and its presence mutex until process exit, including after successful disarming.
    // Stop diagnostics after hook removal so the detach reply can be delivered first.
    // Even a successful worker join does not establish rundown of arbitrary game callbacks.
#ifndef TW3K_RELEASE
    stopControlServer();
#endif
#ifndef TW3K_RELEASE
    removeCrashDumper();
#endif
#ifndef TW3K_RELEASE
    if (g_crashWitnessHandle) {
        if (RemoveVectoredExceptionHandler(g_crashWitnessHandle)) {
            g_crashWitnessHandle = nullptr;
            logf("crash witness: VEH removed");
        } else {
            logf("crash witness: removal failed; keeping handle and DLL; restart required");
        }
    }

    logf("==== tw3k_coop teardown finished; DLL and presence mutex retained until game exit ====");
    logf("Review removal failures above. Restart the game to load another build; --force cannot unload this module.");
#endif
    return 0;
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID)
{
    if (reason == DLL_PROCESS_ATTACH) {
        g_selfModule = hModule;
        DisableThreadLibraryCalls(hModule);
        CreateThread(nullptr, 0, probeThread, nullptr, 0, nullptr);
    }
    return TRUE;
}
